name: Run tests and publish Docker image to harbor.stfc.ac.uk

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Harbor
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Running tests
        run: ./scripts/run_tests.sh

      - name: Log in to Harbor
        run: docker login harbor.stfc.ac.uk -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harbor.stfc.ac.uk/psdi/fastapi-example:${{ github.sha }} .
          docker push harbor.stfc.ac.uk/psdi/fastapi-example:${{ github.sha }}
